### ISSUE TITLE
No search results found - Always

### ISSUE THREAD

**Issue by ashhad** [CoolnsX/dra-cla#14]
I have tried the script on both Linux (debian) and Termux but for both instances I get "No search results found" for any input string.

**Comment by fengbainuo** [comment]
It seems asianembed.io (the site the script scrapes) is down/doesn't forward correctly. We can wait for it to be fixed for now, but I'll look into other sources to use as a backup in case asianembed goes down again in the future

**Comment by ashhad** [comment]
Hey I tried the script from pull request, but looks like it's still not working.

![image](https://github.com/CoolnsX/dra-cla/assets/7990188/68226bf7-be37-45a3-887f-bff9409bceed)

**Comment by fengbainuo** [comment]
weird, it works for me
![image](https://github.com/CoolnsX/dra-cla/assets/97295550/b0df562e-baa5-4597-84c6-6bbaea58fb01)

can you check if your code includes this?
![image](https://github.com/CoolnsX/dra-cla/assets/97295550/79776e67-15e6-4834-83b8-e21a08cce7b7)

**Comment by ashhad** [comment]
It's there

![image](https://github.com/CoolnsX/dra-cla/assets/7990188/674efcc6-022a-4764-af07-a2fc1ec485d0)

**Comment by fengbainuo** [comment]
Interesting, can you send me your output of 
`curl -Ls -o /dev/null -w %{url_effective} https://asianembed.io`
and
`curl -Ls -o /dev/null -w "%{url_effective}" https://dramacool.info`

**Comment by ashhad** [comment]
here you go

![image](https://github.com/CoolnsX/dra-cla/assets/7990188/5972d212-7ca1-4f4d-9cef-ba65d8db6cbe)

thanks for taking out time to help

**Comment by fengbainuo** [comment]
Sure, no problem, helps my bash skills as well, so it's a win-win!

It seems like your second curl won't redirect you correctly, as you can see the output is still dramacool.info, but it should be draplay.info now. I'm not exactly sure what might cause the problem, so here is a few things you can try:

 - try the second curl but withouth the "" around %{url_effective}, and post the output - I don't really think it will solve the problem, but hey, let's try the basics first
 ` curl -Ls -o /dev/null -w %{url_effective} https://dramacool.info`

- in your browser directly look up [https://dramacool.info](https://dranmacool.info) - it should redirect you automatically to https://draplay.info as of writing this message, which should look exactly like how asianembed.io did
![image](https://github.com/CoolnsX/dra-cla/assets/97295550/9ec513fb-9fe5-49b7-81ef-240f820aa7c2)

- curl dramacool directly, with no extra arguments - it should return an error
`curl https://dramacool.info`
![image](https://github.com/CoolnsX/dra-cla/assets/97295550/96dd31f7-142c-4559-83dc-9332081242bf)

- let's see what happens during your curl - this should result in something like this
`curl -w "%{url_effective}\n" -I -L -S https://dramacool.info -o /dev/null`
![image](https://github.com/CoolnsX/dra-cla/assets/97295550/00976425-0f13-4dc3-808e-658670634638)

**Comment by ashhad** [comment]
looks like it's a geolocation issue

![image](https://github.com/CoolnsX/dra-cla/assets/7990188/07638243-5745-48b3-b722-4d5aecc7a33d)

![image](https://github.com/CoolnsX/dra-cla/assets/7990188/7d221fea-2329-4a29-9f7a-021985f47883)

**Comment by CoolnsX** [comment]
I am refactoring script to use fzf (only for drama selection and menu), episode range is typed manually.

**Comment by CoolnsX** [comment]
will release the bare bones on "dev" branch ASAP.

**Comment by CoolnsX** [comment]
Dra-cla is on master branch since months, so maybe ur problem are solved, closing this issue.
