### ISSUE TITLE
Certain queries return "No Results Found"

### ISSUE THREAD

**Issue by zelykiro** [CoolnsX/dra-cla#22]
Searching for series with "special" episodes tends to return "No Results Found", even though the series does exist on the website.

Tested Queris:
1. Mystery to Iunakare
2. Queen of Tears
3. Fox Spirit Matchmaker
4. Romance on the Farm
5. The Inextricable Destiny

![img](https://github.com/user-attachments/assets/d6e1dbfe-47f0-47ec-a2f3-426167e12c87)

**Comment by CoolnsX** [comment]
updated the script. turns out they moved to new domain
