### ISSUE TITLE
[Request] Update Nix package to most recent version

### ISSUE THREAD

**Issue by GreatTeacherOni** [CoolnsX/dra-cla#23]
Would be nice if the nix package could be updated to match the version of the most recent commit in "main" branch. Optimal would be an automated process to do that (i.e. Github Action).

Thanks in advance

**Comment by CoolnsX** [comment]
I don't manage the nix package, someone else does, need to discuss with him on this. Since I don't use nix, so I don't know the syntax for creating the package.

**Comment by GreatTeacherOni** [comment]
@idlip could do that please? Or explain how it's done, in case you don't have the time for it.

**Comment by idlip** [comment]
Hi there, @GreatTeacherOni 

I was late to update, but I had a pr already submitted https://github.com/NixOS/nixpkgs/pull/327949 
I'd need to nudge them to merge.

With the nix version there is nothing much to change except the `rev` and `hash`, and you can build it easily within seconds.

https://pastebin.com/aiCsYWHW (nix file for the script)

so you can do; `nix-build -E 'with import <nixpkgs> {}; callPackage ./<FILENAME>.nix {}'`

and you will have `.result/` directory in that working dir, so `./result/bin/dra-cla` will run the updated tool!

Soon it might be merged, I pinged one of the committer!

**Comment by idlip** [comment]
@GreatTeacherOni Finally, that pr was merged!

**Comment by GreatTeacherOni** [comment]
@idlip Yay! Thank you :)
