### ISSUE TITLE
Search fails due to outdated base_url

### ISSUE THREAD

**Issue by SharkLava** [CoolnsX/dra-cla#7]
![image](https://user-images.githubusercontent.com/28181349/223755370-5a2f9efa-c682-4b1d-abb9-c9bcda1dfc9f.png)

**Comment by Silverslyth** [comment]
same issue here

**Comment by CoolnsX** [comment]
thank you kind user,
As i m very busy with projects, I was unable to look at this issue.. And my mail notifications doesn't work (skill isssue on my phone) looked at this issue via mail
I m gonna merge the PR
thank you again

**Comment by CoolnsX** [comment]
also if u know any drama site that is faster than this site.. please let me know..
suggestions are welcome..
